config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  get  'signup' => 'users#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  resources :lists do
    resources :tasks, except: [:show] do
      patch '/', action: :update_all, on: :collection
      get ':type', action: :index,
                   on: :collection,
                   as: :filtered,
                   constraints: { type: /open|done/ }
      collection do
        get 'remove_completed'
        patch 'update_all'
      end
    end
  end

  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :delete_all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :title, presence: true,
                    length: { minimum: 3 },
                    uniqueness: true

  scope :filtered, ->(type) { send(type) if type }
  scope :done, -> { where(done: true) }
  scope :open, -> { where(done: false) }
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_secure_password
  has_many :lists, dependent: :destroy
  has_many :tasks, through: :lists, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: EMAIL_REGEX, uniqueness: true
  validates :password, length: { minimum: 8 }, on: :create

  after_create :create_default_list

  private

  def create_default_list
    lists.create(title: :default)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def current_list
    @current_list ||= current_user.lists.find(params[:list_id])
  end

  helper_method :current_list

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authorize

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(list_params)
    render(:new) unless @list.save
  end

  def update
    @list = current_user.lists.find(params[:id])
    @list.update(list_params)
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy
  end

  private

  def list_params
    params.fetch(:list).permit(:title, :id_user)
  end

  def lists
    @lists ||= current_user.lists.all
  end

  helper_method :lists

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to list_tasks_path(user.lists.first)
    else
      redirect_to '/login', alert: 'Email or password is incorrect!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login', notice: 'You are logged out!'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize
  before_action :normalize_params, only: :update

  def index
    @task = Task.new
  end

  def create
    @task = current_list.tasks.build(task_params)
    render(:new) unless @task.save
  end

  def update
    @task = current_list.tasks.find(params[:id])
    @task.update(task_params)
  end

  def edit
    @task = current_list.tasks.find(params[:id])
  end

  def update_all
    current_list.tasks.update_all(done: params[:done].present?)
    head :ok, content_type: 'text/html'
  end

  def destroy
    @task = current_list.tasks.find(params[:id])
    @task.destroy
  end

  def remove_completed
    current_list.tasks.where(done: true).delete_all
  end

  private

  def normalize_params
    params[:task] ||= { done: false }
  end

  def task_params
    params.fetch(:task).permit(:title, :done)
  end

  def tasks
    @tasks ||= current_list.tasks.filtered(params[:type]).order(id: :desc)
  end

  helper_method :tasks
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'You signed up successfully'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.fetch(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
      <% end %>
    </header>

    <div class='errors'>
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [current_list, @list], remote: true do |f| %>
  <%= f.text_field :title, autofocus: true, autocomplete: false %>
  <br>
  <%= @list.errors[:title].first %>
<% end %>

app/views/lists/index.html.erb
<% @lists.each do |list| %>

    <h2 ><%= list.title %></h2>

<% end %>
<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1 >New List</h1>


	<%= render 'form' %>

	<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for [current_list, @task], remote: true do |f| %>
  <%= f.text_field :title, autofocus: true, autocomplete: false %>
  <br>
  <%= @task.errors[:title].first %>

  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<li id="task_<%= task.id %>" class="single <%= 'done' if task.done %>">
  <input type='checkbox' name='task[done]' value='1' data-url="<%=list_task_path(current_list, task)%>" data-method="PATCH" data-params='' data-remote <%= 'checked' if task.done %>>
  <%= link_to task.title, edit_list_task_path(current_list, task), remote: true %>
  <%= link_to '×', list_task_path(current_list, task), method: :delete, remote: true, class: 'delete' %>
</li>

app/views/tasks/index.html.erb
<%= link_to 'All', list_tasks_path(current_list) %>
|
<%= link_to 'Done', filtered_list_tasks_path(current_list, :done) %>
|
<%= link_to 'Open', filtered_list_tasks_path(current_list, :open) %>
<hr>

<h1><%= current_list.title %></h1>
<%= render 'form' %>

<input type='checkbox' name='done' id='boss' value='1' data-url="<%= list_tasks_path(current_list) %>" data-method="PATCH" data-remote <%= 'checked' if tasks.all?(&:done) %> >
<ol id='tasks' data-type="<%= params[:type] %>">
  <%= render tasks %>
</ol>

<%= link_to "Remove completed", remove_completed_list_tasks_path,
                                method: :get, remote: true %>

app/views/tasks/remove_completed.js.erb
$('.done').hide(100)

app/views/users/_errors.html.erb
<div class='alert'>
  <ul>
    <% for message in @user.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, remote: true do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit 'Create user'%>
<% end %>